---
- name: Provision Jellyfin Host (WSL Debian)
  hosts: debian-wsl
  become: yes  # Executa tarefas como 'sudo'
  
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600 # 1 hora

    - name: Install dependencies for Docker
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present

    - name: Create directory for Docker GPG key
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Docker GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.gpg
        mode: '0644'
        force: yes

    - name: Add Docker APT repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Ensure Docker Engine and Compose are installed
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: Add user to the 'docker' group
      ansible.builtin.user:
        name: "{{ ansible_user }}" # Usa o usuário definido no inventário (rrant-debian)
        groups: docker
        append: yes
        
    # --- NOVO: TAREFA PARA CRIAR O DIRETÓRIO DE STACK ---
    - name: Ensure stack directory exists
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/stack" # Ou /mnt/d/Projetos/multi/iac-wsl-jellyfin/stack
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'
        
    # --- TAREFA DE GERAÇÃO DO .ENV ---
    - name: Create .env file from template
      ansible.builtin.template:
        src: stack/.env.j2          
        dest: stack/.env            
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0600'